# Generated by Django 4.1.7 on 2023-03-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facebook_Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=30, unique=True)),
                ('about', models.CharField(max_length=30)),
                ('audience', models.CharField(max_length=30)),
                ('rating', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('keyword', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('website', models.CharField(max_length=30)),
            ],
        ),
    ]
