# Generated by Django 4.1.7 on 2023-03-28 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_alter_facebook_pages_about_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linkedin_Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('website', models.URLField(max_length=250, null=True)),
                ('about', models.TextField(null=True)),
                ('link', models.CharField(max_length=250, unique=True)),
                ('audience', models.CharField(max_length=250, null=True)),
                ('keyword', models.CharField(max_length=250, null=True)),
                ('category', models.CharField(max_length=250, null=True)),
                ('location', models.CharField(max_length=250, null=True)),
                ('email', models.EmailField(max_length=250, null=True)),
                ('phone', models.CharField(max_length=250, null=True)),
                ('csize', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Linkedin_Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=250, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('tag', models.CharField(max_length=250)),
                ('timePeriod', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
                ('jobType', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250, null=True)),
                ('keyword', models.CharField(max_length=250, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapper.linkedin_pages')),
            ],
        ),
    ]
